wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1638829308
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      4: 3.8.12
      5: 0.12.7
      6: 4.11.3
      8:
      - 5
